# Generated by Django 4.0.8 on 2023-04-04 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0002_alter_topictag_options_remove_topictag_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("descripiton", models.TextField()),
                ("owner", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Raising Interest", "Trending"),
                            ("Winning Idea", "Winning"),
                            ("Unpublished", "Unpublished"),
                            ("Published", "Published"),
                            ("Evaluation", "Evaluating"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=255,
                    ),
                ),
                ("attachments", models.FileField(default=None, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
