# Generated by Django 4.0.8 on 2023-04-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_alter_idea_attachments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="descripiton",
            new_name="description",
        ),
    ]
