# Generated by Django 4.0.8 on 2023-04-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0003_rename_descripiton_idea_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="engagement_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="is_trending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="idea",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under review", "Under Review"),
                    ("Rejected", "Rejected"),
                    ("Active", "Active"),
                    ("Closed", "Closed"),
                    ("Innovative", "Innovative"),
                ],
                default="Under review",
                max_length=255,
            ),
        ),
    ]
