# Generated by Django 4.0.8 on 2023-08-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0004_idea_engagement_rate_idea_is_trending_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idea",
            options={"ordering": ["-is_trending", "-created_at"]},
        ),
    ]
