stages:
  - test
  - build:image
  - container-scanning
  - deploy:dry-run-verify
  - deploy:helm_chart

# include SAST checking and DAST testing
include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml
  - template: SAST-IaC.gitlab-ci.yml

variables:
  PROJECT_NAME: geo-search-api
  AWS_KMS_REGION: us-east-1
  AWS_KMS_ALIAS: alias/gitlab-runners-infra
  MFA_SERIAL_NUMBER: "arn:aws:iam::303757370730:mfa/gitlab-ideafoundry-infra-production-admin"
  MEMBER_ASSUME_ROLE_NAME: studiox-admin
  POSTGRES_DB: ${PROJECT_NAME}
  POSTGRES_USER: 'local_postgresql_user'
  POSTGRES_PASSWORD: 'local_strong_postgresql_password'
  CONTAINER_SCANNING_DISABLED: "false"
  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  PLATFORM: "linux/amd64"
  ENVIRONMENT_NAME: $CI_ENVIRONMENT_NAME

###
# Templates
###

.before_script_template:
  before_script:
    - apt-get update -y
    - apt-get install -y build-essential gcc libpq-dev
    - pip install -r requirements/dev.txt

.aws_init: &aws_init
  - export AWS_KEY_ID=$(./scripts/kms_decrypt_var.sh $AWS_ACCESS_KEY_ID_ENC)
  - export AWS_SECRET_KEY=$(./scripts/kms_decrypt_var.sh $AWS_SECRET_ACCESS_KEY_ENC)
  - export AWS_ACCESS_KEY_ID=$AWS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
  - |
    if [[ $CI_ENVIRONMENT_NAME == "prod" || $CI_ENVIRONMENT_NAME == "prod-nbs" ]]; then
      CREDS=$(aws sts get-session-token --token-code $TOKEN --serial-number $MFA_SERIAL_NUMBER)
      export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .Credentials.AccessKeyId)
      export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .Credentials.SecretAccessKey)
      export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Credentials.SessionToken)
    fi
  - echo $AWS_ACCESS_KEY_ID | cut -c1-4
  - echo $AWS_SECRET_ACCESS_KEY | cut -c1-4
  - aws sts assume-role --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${MEMBER_ASSUME_ROLE_NAME} --role-session-name geo_search_${CI_ENVIRONMENT_NAME} > aws.json
  - export AWS_ACCESS_KEY_ID=$(jq -r ".Credentials.AccessKeyId" aws.json)
  - export AWS_SECRET_ACCESS_KEY=$(jq -r ".Credentials.SecretAccessKey" aws.json)
  - export AWS_SESSION_TOKEN=$(jq -r ".Credentials.SessionToken" aws.json)
  - rm -f aws.json

.helm_chart: &helm_chart
  - >
    helm upgrade --install ${ADDITIONAL_FLAGS}
    --set releaseTimestamp=$CI_COMMIT_TIMESTAMP
    --set environment=${ENVIRONMENT_NAME}
    --set serviceAccountName=${K8S_SERVICE_ACCOUNT_NAME}
    --set container.image=${ECR_REPOSITORY_URL}:${CI_COMMIT_SHORT_SHA}
    --set application.currentEnvironment=${ENVIRONMENT_NAME}
    --set application.djangoSecretKey=${DJANGO_SECRET_ARN}
    --set application.showTopicsManagementApi=$SHOW_TOPICS_MANAGEMENT_API
    --set application.auth0.domain=${AUTH0_DOMAIN}
    --set application.auth0.issuer=${AUTH0_ISSUER}
    --set application.auth0.apiAudience=${AUTH0_API_AUDIENCE}
    --set application.db.host=$AWS_DB_HOST
    --set application.db.port=$AWS_DB_PORT
    --set application.db.name=$AWS_DB_NAME
    --set application.db.username=$AWS_DB_USERNAME_SECRET_ARN
    --set application.db.password=$AWS_DB_PASSWORD_SECRET_ARN
    --set application.opensearch.host=${AWS_OPENSEARCH_HOST}
    --set application.cloudwatch.logGroup=${CI_ENVIRONMENT_NAME}-${PROJECT_NAME}-logs
    --set application.cloudwatch.streamName=${PROJECT_NAME}
    --set application.cloudwatch.logLevel=${LOG_LEVEL}
    --set network.loadBalancer.subnets="${AWS_LOAD_BALANCER_SUBNETS}"
    --set network.loadBalancer.url=${AWS_LOAD_BALANCER_URL}
    --set replicaCount=1
    --namespace=${CI_ENVIRONMENT_NAME}-${PROJECT_NAME}
    --create-namespace
    geo-search-api ./helm/geo-search-api

.build_docker_container:
  image: docker:24
  services:
    - docker:24-dind
  tags:
    - onward
  variables:
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --update aws-cli jq 
    - export PATH=~/.local/bin:$PATH
    - *aws_init
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
  script:
    - docker pull ${ECR_REPOSITORY_URL}:latest || true
    - |
      docker build \
      --cache-from ${ECR_REPOSITORY_URL}:latest \
      --build-arg BUILD_ENV=$BUILD_ENV \
      --tag ${PROJECT_NAME}:latest --platform ${PLATFORM} --target ${DOCKER_TARGET} .
    - docker tag ${PROJECT_NAME}:latest ${ECR_REPOSITORY_URL}:${CI_COMMIT_SHORT_SHA}
    - |
      if [[ $CI_PIPELINE_SOURCE	== "merge_request_event" ]]; then
        echo "There is a merge request. We don't need to tag this Image as Latest."
      else
        docker tag ${PROJECT_NAME}:latest ${ECR_REPOSITORY_URL}:latest
      fi
    - docker push -a ${ECR_REPOSITORY_URL}

.deploy_docker_container:
  image: alpine/k8s:1.27.7
  tags:
    - onward
  variables:
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
    GRACEFUL_SHUTDOWN_TIME: ${GRACEFUL_SHUTDOWN_TIME}
    MIGRATION_DEADLINE_SECONDS: ${MIGRATION_DEADLINE_SECONDS}
    ADDITIONAL_FLAGS: ""
  before_script:
    - *aws_init
    - aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${EKS_CLUSTER}
  script:
    - *helm_chart

###
# Code Analysis
###

.sast-analyzer:
  allow_failure: false
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"

gemnasium-python-dependency_scanning:
  extends:
    - .ds-analyzer
    - .cyclonedx-reports
    - .before_script_template
  allow_failure: false
  when: always
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"

semgrep-sast:
  allow_failure: false
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"

kics-iac-sast:
  allow_failure: false
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"

container_scanning:
  stage: container-scanning
  tags:
    - onward
  before_script:
    - sudo apt update -y && sudo apt upgrade -y
    - sudo apt-get install python3 awscli jq -y
    - export PATH=~/.local/bin:$PATH
    - *aws_init
    - export AWS_ECR_PASSWORD=$(aws ecr get-login-password --region ${AWS_DEFAULT_REGION})
  variables:
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
    CS_IMAGE: ${ECR_REPOSITORY_URL}:${CI_COMMIT_SHORT_SHA}
    CS_REGISTRY_USER: AWS
    CS_REGISTRY_PASSWORD: "$AWS_ECR_PASSWORD"
    CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "false"
    CS_SEVERITY_THRESHOLD: High
    SECURE_LOG_LEVEL: debug
    GIT_STRATEGY: fetch
  allow_failure: true
  environment:
    name: dev
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"


###
# Build Docker Container
###

mr_api_image:
  stage: build:image
  environment:
    name: dev
  extends:
    - .build_docker_container
  only:
    - merge_requests

dev_api_image:
  stage: build:image
  environment:
    name: dev
  extends:
    - .build_docker_container
  only:
    - develop

stage_api_image:
  stage: build:image
  environment:
    name: stage
  extends:
    - .build_docker_container
  only:
    - stage

prod_api_image:
  stage: build:image
  environment:
    name: prod
  extends:
    - .build_docker_container
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

nbs_api_image:
  stage: build:image
  environment:
    name: prod-nbs
  variables:
    ENVIRONMENT_NAME: prod
  extends:
    - .build_docker_container
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

###
# Deploy Docker Container
###

dev_cluster_resources:
  stage: deploy:helm_chart
  environment:
    name: dev
  extends:
    - .deploy_docker_container
  only:
    - develop

stage_cluster_resources:
  stage: deploy:helm_chart
  environment:
    name: stage
  extends:
    - .deploy_docker_container
  only:
    - stage

prod_cluster_resources:
  stage: deploy:helm_chart
  environment:
    name: prod
  extends:
    - .deploy_docker_container
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

nbs_cluster_resources:
  stage: deploy:helm_chart
  environment:
    name: prod-nbs
  variables:
    ENVIRONMENT_NAME: prod
  extends:
    - .deploy_docker_container
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

###
# Tests Run
###

run_ruff_black_api:
  stage: test
  image: python:3.10-slim-buster
  extends:
    - .before_script_template
  script:
    - make ci_check_code_quality
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"

run_unit_tests_api:
  services:
    - postgres:latest
  stage: test
  image: python:3.10-slim-buster
  variables:
    CURRENT_ENVIRONMENT: gitlab_unit_tests
  extends:
    - .before_script_template
  script:
    - make ci_run_tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"

###
# Helm Dry Run
###

dev_cluster_resources_dry_run:
  stage: deploy:dry-run-verify
  environment:
    name: dev
  extends:
    - .deploy_docker_container
  variables:
    ADDITIONAL_FLAGS: "--dry-run --debug"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

stage_cluster_resources_dry_run:
  stage: deploy:dry-run-verify
  environment:
    name: stage
  extends:
    - .deploy_docker_container
  variables:
    ADDITIONAL_FLAGS: "--dry-run --debug"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "stage"

prod_cluster_resources_dry_run:
  stage: deploy:dry-run-verify
  environment:
    name: prod
  extends:
    - .deploy_docker_container
  variables:
    ADDITIONAL_FLAGS: "--dry-run --debug"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: manual

nbs_cluster_resources_dry_run:
  stage: deploy:dry-run-verify
  environment:
    name: prod-nbs
  extends:
    - .deploy_docker_container
  variables:
    ADDITIONAL_FLAGS: "--dry-run --debug"
    ENVIRONMENT_NAME: prod
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: manual
