# Generated by Django 4.0.7 on 2022-11-13 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "category",
                    models.CharField(
                        choices=[("Post", "Post"), ("Idea", "Idea")], default="Post", max_length=4
                    ),
                ),
                ("creator", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=500)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "ordering": ["created_date"],
            },
        ),
    ]
