# Generated by Django 4.0.8 on 2022-12-21 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="note",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="updated_date",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="note",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="note",
            name="uuid",
        ),
        migrations.AddField(
            model_name="note",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="note",
            name="owner",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(choices=[("Post", "Post"), ("Idea", "Idea")], max_length=255),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(),
        ),
    ]
