# Generated by Django 4.0.8 on 2023-03-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
    ]
