# Generated by Django 4.0.8 on 2023-04-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_notes_like"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="Like", name="index_object_type_object_id"),
        migrations.RemoveConstraint(model_name="Like", name="unique_object_type_object_id_user_id"),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
