# Generated by Django 4.0.8 on 2023-04-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_delete_like"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
