# Generated by Django 4.0.8 on 2023-04-13 12:48

from django.db import migrations, models
import django.db.models.deletion
import geo_search_api.apps.likes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("object_id", models.UUIDField()),
                ("owner", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
            bases=(models.Model, geo_search_api.apps.likes.models.LikeModelMixin),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["object_type", "object_id"], name="comment_index_type_id"),
        ),
    ]
