# Generated by Django 4.0.8 on 2023-08-02 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ideas", "0005_alter_idea_options"),
        ("topics", "0010_auto_20230829_0222"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Innovator", "Innovator"), ("Accelorator", "Accelorator")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("prize", models.CharField(max_length=255, blank=True, null=True)),
                (
                    "idea",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ideas.idea"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topics.topic"
                    ),
                ),
            ],
        ),
    ]
