# Generated by Django 4.0.8 on 2023-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Innovator", "Innovator"), ("Accelerator", "Accelerator")],
                max_length=255,
                null=True,
            ),
        ),
    ]
