# Generated by Django 4.0.8 on 2023-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_type_id_user",
        ),
        migrations.RemoveIndex(
            model_name="like",
            name="index_type_id",
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["object_type", "object_id"], name="like_index_type_id"),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("object_type", "object_id", "user_id"), name="like_unique_type_id_user"
            ),
        ),
    ]
