"""
Django settings for geo_search_api project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from corsheaders.defaults import default_headers

from geo_search_api.environments import Environment

environment = Environment.create_env()
CURRENT_ENVIRONMENT = environment.current_environment

AWS_REGION_NAME = environment.aws_region_name
AWS_OPENSEARCH_HOST = environment.aws_opensearch_host
AWS_SERVICE_NAME = environment.aws_service_name
PROJECT_NAME = environment.project_name

CORS_ALLOW_ALL_ORIGINS = environment.cors_allow_all_origins
CORS_ALLOW_CREDENTIALS = environment.cors_allow_credentials
CORS_ALLOW_HEADERS = list(default_headers) + environment.cors_allow_headers

LOGGING = environment.logging

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environment.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environment.debug

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = environment.installed_apps

MIDDLEWARE = environment.middleware

REST_FRAMEWORK = environment.rest_framework

ROOT_URLCONF = environment.root_urlconf

TEMPLATES = environment.templates

WSGI_APPLICATION = environment.wsgi_application

# databases
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = environment.databases

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = environment.auth_password_validators

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = environment.language_code

TIME_ZONE = environment.time_zone

USE_I18N = environment.use_i18n

USE_L10N = environment.use_l10n

USE_TZ = environment.use_tz

AUTH0_DOMAIN = environment.auth0_domain
AUTH0_ISSUER = environment.auth0_issuer
AUTH0_API_AUDIENCE = environment.auth0_api_audience
AUTH0_ALGORITHMS = environment.auth0_algorithms

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = environment.static_url

SPECTACULAR_SETTINGS = environment.spectacular_settings

SHOW_TOPICS_MANAGEMENT_API = environment.show_topics_management_api

# Likes settings
LIKES_OBJECT_TYPES = environment.likes_object_types

# Comments settings
COMMENTS_OBJECT_TYPES = environment.comments_object_types

# OpenSearch parameters
MAX_SEARCHING_SIZE = environment.opensearch_max_searching_size
MAX_TERMS_AGGREGATION_SIZE = environment.opensearch_max_terms_aggregation_size
MAX_TERMS_AGGREGATION_CLUSTERS = environment.opensearch_max_terms_aggregation_clusters
MAX_BUCKETS_AGGREGATION_SIZE = environment.opensearch_max_buckets_aggregation_size
