# Generated by Django 4.0.8 on 2023-03-28 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TopicStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "topic_stage",
            },
        ),
        migrations.CreateModel(
            name="TopicTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "topic_tag",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("owner", models.CharField(max_length=255)),
                (
                    "topic_type",
                    models.CharField(
                        choices=[("Experimentation", "Experimentation"), ("Moonshot", "Moonshot")],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("prize", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="topics.topicstage"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, null=True, to="topics.topictag")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
