# Generated by Django 4.0.8 on 2023-04-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_alter_topictag_options_remove_topictag_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topictag",
            old_name="uuid",
            new_name="id",
        ),
    ]
