# Generated by Django 4.0.8 on 2023-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_rename_uuid_topictag_id_alter_topicstage_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="tags",
        ),
        migrations.AddField(
            model_name="topic",
            name="tags",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
