# Generated by Django 4.0.8 on 2023-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_remove_topic_tags_topic_tags_alter_topicstage_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="tags",
        ),
        migrations.AddField(
            model_name="topic",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="topics.topictag"),
        ),
    ]
