# Generated by Django 4.0.8 on 2023-04-05 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_remove_topic_tags_topic_tags_alter_topicstage_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topicstage",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="topicstage",
            name="id",
        ),
        migrations.AddField(
            model_name="topicstage",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="topicstage",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
