# Generated by Django 4.0.8 on 2023-04-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0006_alter_topicstage_options_remove_topicstage_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topicstage",
            old_name="uuid",
            new_name="id",
        ),
    ]
