# Generated by Django 4.0.8 on 2023-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0007_rename_uuid_topicstage_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="stage",
        ),
        migrations.AddField(
            model_name="topic",
            name="stage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
