# Generated by Django 4.0.8 on 2023-04-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0008_alter_topic_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="stage",
        ),
        migrations.AddField(
            model_name="topic",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="topics.topicstage"
            ),
        ),
    ]
