# Generated by Django 4.0.8 on 2023-08-29 02:22

from django.db import migrations


def add_evaluation_and_closed_stages(apps, schema_editor):
    TopicStage = apps.get_model("topics", "TopicStage")
    TopicStage.objects.get_or_create(name="Evaluation")
    TopicStage.objects.get_or_create(name="Closed")


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0009_alter_topic_stage"),
    ]

    operations = [
        migrations.RunPython(add_evaluation_and_closed_stages),
    ]
